imports:
    - { resource: "@SyliusCmsPlugin/Resources/config/grids/admin.yml" }
    - { resource: "@SyliusCmsPlugin/Resources/config/grids/shop.yml" }

sylius_grid:
    templates:
        action:
            import: "@SyliusCmsPlugin/Grid/Action/import.html.twig"
