bitbag_sylius_cms_plugin_shop_collection_show:
    path: /collection/{code}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.collection::showAction
        _sylius:
            template: $template
            repository:
                method: findOneByCode
                arguments:
                    - $code
                    - "expr:service('sylius.context.locale').getLocaleCode()"

bitbag_sylius_cms_plugin_shop_collection_show_codes:
    path: /collections/{codes}
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_cms_plugin.controller.collection::indexAction
        _sylius:
            template: $template
            repository:
                method: findByCodesAndLocale
                arguments:
                    - $codes
                    - "expr:service('sylius.context.locale').getLocaleCode()"

