sylius_resource:
    resources:
        sylius_cms_plugin.collection:
            driver: doctrine/orm
            classes:
                model: Sylius\CmsPlugin\Entity\Collection
                interface: Sylius\CmsPlugin\Entity\CollectionInterface
                form: Sylius\CmsPlugin\Form\Type\CollectionType
                repository: Sylius\CmsPlugin\Repository\CollectionRepository
                factory: Sylius\Component\Resource\Factory\Factory
