sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.collection:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusCmsPlugin\Entity\Collection
                interface: BitBag\SyliusCmsPlugin\Entity\CollectionInterface
                form: BitBag\SyliusCmsPlugin\Form\Type\CollectionType
                repository: BitBag\SyliusCmsPlugin\Repository\CollectionRepository
                factory: Sylius\Component\Resource\Factory\Factory
