sylius_resource:
  resources:
    bitbag_sylius_cms_plugin.content_configuration:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusCmsPlugin\Entity\ContentConfiguration
        interface: BitBag\SyliusCmsPlugin\Entity\ContentConfigurationInterface
        form: BitBag\SyliusCmsPlugin\Form\Type\ContentConfigurationType
        repository: BitBag\SyliusCmsPlugin\Repository\ContentConfigurationRepository
        factory: Sylius\Component\Resource\Factory\TranslatableFactory
