sylius_resource:
  resources:
    sylius_cms_plugin.content_configuration:
      driver: doctrine/orm
      classes:
        model: Sylius\CmsPlugin\Entity\ContentConfiguration
        interface: Sylius\CmsPlugin\Entity\ContentConfigurationInterface
        form: Sylius\CmsPlugin\Form\Type\ContentConfigurationType
        repository: Sylius\CmsPlugin\Repository\ContentConfigurationRepository
        factory: Sylius\Component\Resource\Factory\TranslatableFactory
