sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.media:
            driver: doctrine/orm
            classes:
                model: Sylius\CmsPlugin\Entity\Media
                interface: Sylius\CmsPlugin\Entity\MediaInterface
                form: Sylius\CmsPlugin\Form\Type\MediaType
                repository: Sylius\CmsPlugin\Repository\MediaRepository
                controller: Sylius\CmsPlugin\Controller\MediaController
                factory: Sylius\Component\Resource\Factory\TranslatableFactory
            translation:
                classes:
                    model: Sylius\CmsPlugin\Entity\MediaTranslation
                    interface: Sylius\CmsPlugin\Entity\MediaTranslationInterface
