sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.page:
            driver: doctrine/orm
            classes:
                model: Sylius\CmsPlugin\Entity\Page
                interface: Sylius\CmsPlugin\Entity\PageInterface
                form: Sylius\CmsPlugin\Form\Type\PageType
                repository: Sylius\CmsPlugin\Repository\PageRepository
                controller: Sylius\CmsPlugin\Controller\PageController
                factory: Sylius\Component\Resource\Factory\TranslatableFactory
            translation:
                classes:
                    model: Sylius\CmsPlugin\Entity\PageTranslation
                    interface: Sylius\CmsPlugin\Entity\PageTranslationInterface
