sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.template:
            driver: doctrine/orm
            classes:
                model: Sylius\CmsPlugin\Entity\Template
                interface: Sylius\CmsPlugin\Entity\TemplateInterface
                form: Sylius\CmsPlugin\Form\Type\TemplateType
                repository: Sylius\CmsPlugin\Repository\TemplateRepository
                factory: Sylius\Component\Resource\Factory\Factory
                controller: Sylius\CmsPlugin\Controller\TemplateController
