sylius_grid:
    grids:
        sylius_cms_plugin_admin_collection:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius_cms_plugin.model.collection.class%"
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                name:
                    type: twig
                    label: sylius_cms_plugin.ui.name
                    sortable: name
                    path: .
                    options:
                        template: "@BitBagSyliusCmsPlugin/Grid/Field/name.html.twig"
                code:
                    type: string
                    label: sylius_cms_plugin.ui.code
                    sortable: ~
                type:
                    type: string
                    label: sylius_cms_plugin.ui.type
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
