sylius_grid:
    grids:
        bitbag_sylius_cms_plugin_admin_collection:
            driver:
                name: doctrine/orm
                options:
                    class: "%bitbag_sylius_cms_plugin.model.collection.class%"
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                name:
                    type: string
                    label: bitbag_sylius_cms_plugin.ui.name
                    sortable: translation.name
                code:
                    type: string
                    label: bitbag_sylius_cms_plugin.ui.code
                    sortable: ~
                type:
                    type: string
                    label: bitbag_sylius_cms_plugin.ui.type
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
