sylius_grid:
    grids:
        sylius_cms_admin_template:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius_cms.model.template.class%"
            sorting:
                name: asc
            limits: [10, 25, 50]
            fields:
                name:
                    type: twig
                    label: sylius_cms.ui.name
                    sortable: name
                    path: .
                    options:
                        template: "@SyliusCmsPlugin/Grid/Field/name.html.twig"
                type:
                    type: string
                    label: sylius.ui.type
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [name]
                enabled:
                    type: boolean
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
