sylius_cms_admin_ajax_taxon_by_name_phrase:
    path: /ajax/taxon/search-by-name
    methods: [GET]
    defaults:
        _format: json
        _controller: sylius_cms.controller.action.admin.taxon_search
